name: "infra preview & deploy"

on:
  push:
    branches:
      - main
    paths:
      - 10_infra/**
      - .github/workflows/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-1
  TF_VERSION: 1.2.8
  TF_PROJECT: tastylog
  TF_ENVIRONMENT: dev

defaults:
  run:
    shell: bash
    working-directory: "10_infra/"

jobs:
  preview:
    name: "Preview"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{env.TF_VERSION}}
      - name: Terraform format
        run: 
          terraform fmt -check
      - name: Configure AWS credential  
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{env.AWS_REGION}}
          role-to-assume: ${{secrets.AWS_ROLE_ARN}}
      - name: Terraform init
        run:
          terraform init -no-color
      - name: Terraform validate
        run:
          terraform validate -no-color
      - name: Terraform Plan
        run:
         terraform plan \
           -var 'project=${{env.TF_PROJECT}}' \
           -var 'environment=${{env.TF_ENVIRONMENT}}' \
           -var 'username=${{secrets.MYSQL_USERNAME}}' \
           -var 'password=${{secrets.MYSQL_PASSWORD}}' \
           -input=false \
           -no-color \
           -detailed-exitcode


